src/GPDS/GPDS/urls.py
from GPDS import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'GPDS.views.home', name='home'),
    # url(r'^GPDS/', include('GPDS.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/',     include(admin.site.urls)),
    url(r'^$', 'GPDS.views.home', name='home'),
    url(r'^version/$', 'GPDS.views.version', name='version'),
    url(r'^authors/$', 'GPDS.views.authors', name='authors'),
    url(r'^license/$', 'GPDS.views.license', name='license'),
    url(r'^tutorial/$', 'GPDS.views.tutorial', name='tutorial'),
    url(r'^support/$', 'GPDS.views.support', name='support'),
    url(r'^help/$', 'GPDS.views.help', name='help'),
    url(r'^users/',     include('users.urls')),
    url(r'^methodology/', include('methodology.urls')),
    url(r'^project/',   include('project.urls')),
    url(r'^activity/',  include('activity.urls')),
    url(r'^social/',  include('social.urls')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

src/GPDS/project/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # URL's for Project
    url(r'^manage_project/$', 'project.views.manage_project'),
    
    url(r'^create_project/$', 'project.views.create_project'),
    
    url(r'^read_project/(?P<project_id>\d+)/$', 'project.views.read_project'),
    
    url(r'^update_project/(?P<project_id>\d+)/$', 'project.views.update_project'),
    
    url(r'^delete_project/(?P<project_id>\d+)/$', 'project.views.delete_project'),
    
    url(r'^quit_project/$', 'project.views.quit_project'),
    
    url(r'^manage_participants/(?P<project_id>\d+)/$','project.views.manage_participants'),
    
    url(r'^add_participant_project/(?P<project_id>\d+)/$','project.views.add_participant_project'),
    
    url(r'^read_role/$','project.views.read_role'),
    
    url(r'^(?P<project_id>\d+)/create_artifact$', 'activity.views.create_artifact'),
)

src/GPDS/project/models.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from methodology.models import Methodology
from users.models import Membership

# Create your models here.

class Project(models.Model):
    AREA_CHOICES = (
          ('CO', 'Computacion'),
          ('EL', 'Electrica'),
          ('EC', 'Electronica'),   
          ('MA', 'Matematica'),
          ('FI', 'Fisica' ),
          ('QU', 'Quimica'),
          ('OT', 'Otro')       
    )
    name = models.CharField(max_length=30)
    description = models.TextField()
    date_start = models.DateTimeField('date started')
    date_end = models.DateTimeField('date ended')
    cost  = models.DecimalField(max_digits=19, decimal_places=10)
    area = models.CharField(max_length=2, choices=AREA_CHOICES, default='CO')
    methodology = models.ForeignKey(Methodology)
    leader = models.ForeignKey(User, related_name='project_leader',null=True, blank=True)
    participants = models.ManyToManyField(User,null=True, blank=True, through=Membership)
    enabled = models.BooleanField(default=True)
    
    def __unicode__(self):
        return self.name
    
admin.site.register(Project)
    

src/GPDS/project/views.py
from django.template import Context, loader
from project.models import Project 
from activity.models import Activity
from users.models import Membership,Role
from methodology.models import Methodology, SoftwareProcess
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, login_required, permission_required
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_protect
from project.form import ProjectChangeForm, ProjectDeleteForm, ProjectCreateForm, ProjectManageParticipants, MembershipCreateForm
from sets import Set
from django.utils import timezone

###################################################################################################
#                                 Manage, CRUD, Quit for Project                                  #
###################################################################################################

@login_required
def manage_project(request):
    participant_projects = Set([])
    lider_projects = Project.objects.filter(leader__id=request.user.id, enabled=True)
    projects_aux = Project.objects.filter(participants__id=request.user.id, enabled=True)
    for project_aux in projects_aux:
        if(project_aux not in lider_projects):
            participant_projects.add(project_aux)
    return render_to_response('project/manage_project.html', {'lider_projects'      :lider_projects, 
                                                              'participant_projects':participant_projects},
                              context_instance=RequestContext(request))

# Hay que cambiarlo
@login_required
def create_project(request):
    if request.method == 'POST':
        form = ProjectCreateForm(request.POST)
        if form.is_valid():
            form.save()
        p = get_object_or_404(Project,name=request.POST['name'], leader=request.user)
        membership = Membership(user=request.user, project=p)
        membership.save()
        projects = Project.objects.filter(name='Prototype', leader__username='admin', methodology__pk=request.POST['methodology'], 
                                          enabled=True)
        
        if projects.count() == 1:
            project = projects.get()
            activities = Activity.objects.filter(project=project)
            for activity in activities: 
                pk_activity = activity.pk
                activity.pk = None
                activity.date_start = timezone.now()
                activity.date_end = timezone.now()
                activity.project = p
                activity_aux = get_object_or_404(Activity,pk=pk_activity)
                activity.save()
                activity.activities_required = activity_aux.activities_required.all()
                activity.activities_super = activity_aux.activities_super.all()
                activity.save()
                
            activities = Activity.objects.filter(project=p)
            for activity in activities:
                
                activities_required = activity.activities_required.all()
                activities_clone_required = []
                for activity_required in activities_required:
                    activities_clone_required.append(get_object_or_404(Activity, name=activity_required.name, project=p))
                
                activities_super = activity.activities_super.all()
                activities_clone_super = []    
                for activity_super in activities_required:
                    activities_clone_super.append(get_object_or_404(Activity, name=activity_super.name, project=p))
                             
                activity.activities_required = activities_clone_required
                activity.activities_super    = activities_clone_super
                activity.save()        
                
        return manage_project(request) 
    else:
        # m = Methodology.objects.filter(is_private=True, enabled=True)
        form = ProjectCreateForm(initial={'leader':request.user})
        return render_to_response('project/create_project.html', {'form':form,}, context_instance=RequestContext(request))

@login_required
def read_project(request,project_id):
    try:
        p = Project.objects.get(pk=project_id)
    except Poll.DoesNotExist:
        raise Http404
    return render_to_response('project/read_project.html', {'project': p},
                                context_instance=RequestContext(request))
     
@login_required
def update_project(request, project_id):
    if request.method == 'POST':
        form = ProjectChangeForm(request.POST, instance=Project.objects.get(pk=project_id))
        redirect_to = request.REQUEST.get('next', reverse('project.views.manage_project', args=()))
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('project.views.manage_project', args=()))
    else:
        form = ProjectChangeForm(instance=Project.objects.get(pk=project_id))
        redirect_to = request.REQUEST.get('next', '')
    return render_to_response('project/update_project.html',
                              {'form':form,
                               'next':redirect_to,
                               'project_id':project_id},
                                 context_instance=RequestContext(request))

@login_required 
def delete_project(request, project_id):
    if request.method == 'POST':    
        form = ProjectDeleteForm(request.POST, instance=Project.objects.get(pk=project_id))
        redirect_to = request.REQUEST.get('next', reverse('project.views.manage', args=()))
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('project.views.manage', args=()))
    else:
        form = ProjectDeleteForm(instance=Project.objects.get(pk=project_id))
        redirect_to = request.REQUEST.get('next', '')
    return render_to_response('project/delete_project.html',
                              {'form':form,
                               'next':redirect_to,
                               'project_id':project_id},
                              context_instance=RequestContext(request))

@login_required
def quit_project(request):
    memberships = Membership.objects.filter(user_id=request.user.id,project_id=request.POST['project_id'])
    memberships.delete()
    return HttpResponseRedirect(reverse('project.views.manage_project', args=()))

@login_required
def read_role(request):
    if request.method == 'POST':
       	return read_methodology(request, methodology_id=p.id)
    else:
	Lista_Proyectos=SoftwareProcess.objects.all()
        return render_to_response('project/read_role.html',
				{
        			'Lista_Proyectos': Lista_Proyectos,
    				},
                              context_instance=RequestContext(request))

#FALTA POR TERMIANR Y PROBAR
@login_required
def manage_participants(request,project_id):
    redirect_to = request.REQUEST.get('next', '')
    return render_to_response('project/manage_participants.html',
                              {'next':redirect_to,
                               'project_id':project_id},
                                 context_instance=RequestContext(request))
    
@login_required
def add_participant_project(request,project_id):
    if request.method == 'POST':
        form = MembershipCreateForm(request.POST, instance=Project.objects.get(pk=project_id))
        redirect_to = request.REQUEST.get('next', reverse('project.views.manage_participants', args=()))
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('project.views.manage_participants', args=()))
    else:
        #projects_obj = Project.objects.filter( name = 'proj1')
        form = MembershipCreateForm(instance=Project.objects.get(pk=project_id))
        redirect_to = request.REQUEST.get('next', '')

    return render_to_response('project/add_participant_project.html',
                              {'form':form,
                               'next':redirect_to,
                               'project_id':project_id},
                                 context_instance=RequestContext(request))    

src/GPDS/templates/project/add_participant_project.html
{% extends "base.html" %}

{% block content %}



<form action="/project/manage_participants/{{ project_id }}/{% if next %}?next={{ next }}{% endif %}" method="POST" >
    {% csrf_token %}
    <h1>Agregar Participante y Membresia</h1>
    Proyecto:  project_id
    <br/>
    Participante: {{form.user}}
    <br/>
    Rol: {{form.role}}
    <br/>    
    Fecha de Suscripcion: {{form.date_joined}}
    <br/>
    Activo: {{form.enabled}}
    <br/>	
	<input type="submit" value="Guardar" />
</form>

{% endblock %}

src/GPDS/templates/project/create_project.html
{% extends "base.html" %}

{% block content %}
<script type="text/javascript"> 
  $(function(){
    $("#id_date_start").datepicker();
    $("#id_date_end").datepicker();
  });
</script>

{% if user.is_authenticated %}
        <h1>Nuevo Proyecto</h1>

        <form action="" method="POST" >
	        {% csrf_token %}
	        <table>
	        {{ form.as_table }}
	        </table>
	        <button type="submit" class="submit btn primary-btn"> Crear </button>
        </form> 
{% else %}
        <p>Primero debe iniciar sesión</p>
{% endif %}

{% endblock %}
         

src/GPDS/templates/project/delete_project.html
{% extends "base.html" %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="/project/delete/{{ project_id }}/{% if next %}?next={{ next }}{% endif %}" method="POST" >
	{% csrf_token %}
	<table>
	{{ form.as_table }}
	</table>
	<input type="submit" value="Eliminar" />
</form>

{% endblock %}

src/GPDS/templates/project/manage_participants.html
{% extends "base.html" %}

{% block content %}


	<a href="/project/add_participant_project/{{project_id}}/">Agregar Participantes</a>
    <br/>
    <a href="/project/invitePart/">Invitar Participantes</a>
    <br/>    
    <br/>


{% endblock %}

src/GPDS/templates/project/manage_project.html
{% extends "base.html" %}

# Display a list of applications
# requires a variable 'objects_list' of type query_set

{% block content %}

<div class="manage-box">

<h1 style="font-size:20px;"> Selecciona una opcion </h1>
</br>
<a href="/project/create_project/" class="submit btn primary-btn">Crear nuevo proyecto</a>
<a href="/project/read_role/" class="submit btn primary-btn">Listar roles de proyectos</a>
</br></br><hr/>

<h1 style="font-size:20px;"> Proyectos que lidero </h1>
</br>

{% if lider_projects %}

	{% for p in lider_projects %}
		<a href="/project/read_project/{{p.id}}/" class="submit btn primary-btn">     {{ p.name }} </a>
		<a href="/activity/manage_activity/{{p.id}}/" class="submit btn primary-btn"> Gestionar    </a>
		<a href="/project/update_project/{{p.id}}/" class="submit btn primary-btn">   Editar       </a>
	    <a href="/project/delete_project/{{p.id}}/" class="submit btn primary-btn">   Eliminar     </a>
	    <a href="/social/request_join_project/{{p.id}}/" class="submit btn primary-btn">   Invitar usuario     </a>
	    </br></br>
	{% endfor %}
	
{% else %}
	Usted no es lider de ningun proyecto.
{% endif %}

</br><hr/>

<h1 style="font-size:20px;"> Proyectos en los que participo </h1>
</br>
{% if participant_projects %}
	
	{% for p in participant_projects %}

	    	<a href="/project/read_project/{{p.id}}/" class="submit btn primary-btn"> {{ p.name }} </a>
	    	<a href="/activity/manage_activity/{{p.id}}/" class="submit btn primary-btn"> Gestionar </a>
			<form action="/project/quit_project/" method="POST">    	
			{% csrf_token %}
				<button type="submit" name="project_id" value="{{p.id}}" class="submit btn primary-btn"> Abandonar </button>
			</form>			
			</br></br>
	{% endfor %}


{% else %}
	Usted no participa en ningun proyecto.
{% endif %}
</br>

</div>

{% endblock %}	

src/GPDS/templates/project/read_project.html
{% extends "base.html" %}

{% block content %}
<script type="text/javascript"> 
  $(function(){
    $("#id_date_start").datepicker();
    $("#id_date_end").datepicker();
  });
</script>

<div class="read-box" style="background-color:#000000;">

<h1 style="font-size:20px;">{{ project.name }}</h1>
<ul>
    Descripción: {{ project.description }}<br>
    Fecha de Inicio: {{ project.date_start }}<br>
    Fecha de Culminación: {{ project.date_end }}<br>
    Costo del Proyecto: {{ project.cost }}<br>
    Area del Proyecto: {{ project.area }}<br>
    Metodología del Proyecto: {{ project.methodology.name }}<br>
    Lider del Proyecto: {{ project.leader }}<br></br>
    <a href="/project/manage_project/"> Regresar </a>
</ul>

</div>

{% endblock %}

src/GPDS/templates/project/update_project.html
{% extends "base.html" %}

{% block content %}

<script type="text/javascript"> 
  $(function(){
    $("#id_date_start").datepicker();
    $("#id_date_end").datepicker();
  });
</script>


<form action="/project/update_project/{{ project_id }}/{% if next %}?next={{ next }}{% endif %}" method="POST" >
	{% csrf_token %}
	<table>
	{{ form.as_table }}
	</table>
    <br/> 
    <br/>
	<input type="submit" value="Guardar" />
</form>

{% endblock %}